### ISSUE TITLE
tide-jump-to-definition randomly work with default exports

### ISSUE THREAD

**Issue by cescoferraro** [ananthakumaran/tide#154]
## Component 1

```
export default ({ }) => {
    return <div><h2>jsjsjs</h2></div>
}
```
## Component 2

```
export const Test = ({ }) => {
    return <div><h2>jsjsjs</h2></div>
}
```
## Usage
```
//  tide-jump-to-definition does not work here 
import Test from "./test"
//  tide-jump-to-definition work here 
import {Test} from "./test"
```

## LOGS
```
(achars-4d8010661a) tsserver server started successfully.
Error processing request. Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at createDefinitionInfo (/Users/cesco/go/src/github.com/cescoferraro/dotfiles/src/emacs.d/.cask/25.2/elpa/tide-20170513.1211/tsserver/tsserver.js:77157:53)
    at Object.getDefinitionAtPosition (/Users/cesco/go/src/github.com/cescoferraro/dotfiles/src/emacs.d/.cask/25.2/elpa/tide-20170513.1211/tsserver/tsserver.js:77032:25)
    at Object.getDefinitionAtPosition (/Users/cesco/go/src/github.com/cescoferraro/dotfiles/src/emacs.d/.cask/25.2/elpa/tide-20170513.1211/tsserver/tsserver.js:86768:38)
    at IOSession.Session.getDefinition (/Users/cesco/go/src/github.com/cescoferraro/dotfiles/src/emacs.d/.cask/25.2/elpa/tide-20170513.1211/tsserver/tsserver.js:92572:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/cesco/go/src/github.com/cescoferraro/dotfiles/src/emacs.d/.cask/25.2/elpa/tide-20170513.1211/tsserver/tsserver.js:92131:61)
    at /Users/cesco/go/src/github.com/cescoferraro/dotfiles/src/emacs.d/.cask/25.2/elpa/tide-20170513.1211/tsserver/tsserver.js:93451:88
    at IOSession.Session.executeWithRequestId (/Users/cesco/go/src/github.com/cescoferraro/dotfiles/src/emacs.d/.cask/25.2/elpa/tide-20170513.1211/tsserver/tsserver.js:93442:28)
    at IOSession.Session.executeCommand (/Users/cesco/go/src/github.com/cescoferraro/dotfiles/src/emacs.d/.cask/25.2/elpa/tide-20170513.1211/tsserver/tsserver.js:93451:33)
    at IOSession.Session.onMessage (/Users/cesco/go/src/github.com/cescoferraro/dotfiles/src/emacs.d/.cask/25.2/elpa/tide-20170513.1211/tsserver/tsserver.js:93471:35)
    at Interface.<anonymous> (/Users/cesco/go/src/github.com/cescoferraro/dotfiles/src/emacs.d/.cask/25.2/elpa/tide-20170513.1211/tsserver/tsserver.js:94692:27)
Mark set
evil-line-move: End of buffer [4 times]

```

**Comment by josteink** [comment]
The first component doesn't export any Test. Does that example even compile?

Also: if anything, this seems like an issue with tsserver, not tide.

**Comment by ananthakumaran** [comment]
This is a problem in tsserver, it should never throw out error. Please open an issue in https://github.com/Microsoft/TypeScript with the same info.

**Comment by ananthakumaran** [comment]
Closing this. Please re-open if there is any problem in tide.
