### ISSUE TITLE
No completions for types from global scope

### ISSUE THREAD

**Issue by sk1e** [ananthakumaran/tide#181]
Hi, with this code sample:
```typescript
interface Named { }; 
const x: Nam
```
I don't get completion for "Named" interface.
Response for "completions" request while typing "Nam" after "const x: " is as follows:
```
(:seq 0 :type response :command completions :request_seq 1361 :success :json-false :message Error processing request. Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at symbolsToArray (/home/kotik/.emacs.d/.cask/25.2/elpa/tide-20170720.2101/tsserver/tsserver.js:32377:20)
    at Object.getExportsOfModuleAsArray [as getExportsOfModule] (/home/kotik/.emacs.d/.cask/25.2/elpa/tide-20170720.2101/tsserver/tsserver.js:28289:20)
    at symbolCanbeReferencedAtTypeLocation (/home/kotik/.emacs.d/.cask/25.2/elpa/tide-20170720.2101/tsserver/tsserver.js:76446:55)
    at /home/kotik/.emacs.d/.cask/25.2/elpa/tide-20170720.2101/tsserver/tsserver.js:76408:36
    at Object.filter (/home/kotik/.emacs.d/.cask/25.2/elpa/tide-20170720.2101/tsserver/tsserver.js:1637:25)
    at filterGlobalCompletion (/home/kotik/.emacs.d/.cask/25.2/elpa/tide-20170720.2101/tsserver/tsserver.js:76390:27)
    at tryGetGlobalSymbols (/home/kotik/.emacs.d/.cask/25.2/elpa/tide-20170720.2101/tsserver/tsserver.js:76386:27)
    at getCompletionData (/home/kotik/.emacs.d/.cask/25.2/elpa/tide-20170720.2101/tsserver/tsserver.js:76237:22)
    at Object.getCompletionsAtPosition (/home/kotik/.emacs.d/.cask/25.2/elpa/tide-20170720.2101/tsserver/tsserver.js:75754:34)
    at Object.getCompletionsAtPosition (/home/kotik/.emacs.d/.cask/25.2/elpa/tide-20170720.2101/tsserver/tsserver.js:89905:35))
```
It worked fine for me earlier and it stopped working after update to 20170720.2101.

**Comment by ananthakumaran** [comment]
This is an issue in `tsserver`. Can you open a new issue here https://github.com/Microsoft/TypeScript/issues/new

**Comment by sk1e** [comment]
@ananthakumaran looks like this issue is resolved in the latest version. Do we have any reasons for not upgrading to it?

**Comment by ananthakumaran** [comment]
nope. fixed in master.
