### ISSUE TITLE
syntax checker error

### ISSUE THREAD

**Issue by it6** [ananthakumaran/tide#239]
I see this error in mini buffer when ever I save a file containing `set()`

```
Error from syntax checker typescript-tide: Error processing request. Debug Failure.
Error: Debug Failure.
    at checkUnusedClassMembers (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:43583:38)
    at checkUnusedIdentifiers (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:43467:29)
    at checkSourceFileWorker (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:46141:21)
    at checkSourceFile (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:46114:13)
    at getDiagnosticsWorker (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:46179:17)
    at Object.getDiagnostics (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:46165:24)
    at /Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:74447:85
    at runWithCancellationToken (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:74410:24)
    at getSemanticDiagnosticsForFileNoCache (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:74433:20)
    at getAndCacheDiagnostics (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:74669:26)
    at getSemanticDiagnosticsForFile (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:74430:20)
    at getDiagnosticsHelper (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:74372:24)
    at Object.getSemanticDiagnostics (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:74385:20)
    at Object.getSemanticDiagnostics (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:99631:47)
    at /Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:107448:140
    at IOSession.Session.getDiagnosticsWorker (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:107335:35)
    at IOSession.Session.getSemanticDiagnosticsSync (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:107448:29)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:106962:61)
    at /Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:108343:88
    at IOSession.Session.executeWithRequestId (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:108334:28)
    at IOSession.Session.executeCommand (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:108343:33)
    at IOSession.Session.onMessage (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:108363:35)
    at Interface.<anonymous> (/Users/kotamrs/.emacs.d/elpa/tide-20180205.413/tsserver/tsserver.js:109624:27)
    at Interface.emit (events.js:160:13)
    at Interface._onLine (readline.js:287:10)
    at Interface._normalWrite (readline.js:435:12)
    at Socket.ondata (readline.js:146:10)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onread (net.js:602:20)
```

Here is the sample file 
```
export class test {
  set val() {};
}
```

Don't see error message after removing/commenting `set()`.

Here is my `tsconfig`

```
  "compileOnSave": false,
  "compilerOptions": {
    "noUnusedLocals": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "../out-tsc-e2e",
    "sourceMap": true,
    "target": "es5"
  }
```

**Comment by ananthakumaran** [comment]
does it happen with older typescript/tsserver? This looks like an issue with tsserver. I would suggest to open an issue in https://github.com/Microsoft/TypeScript
