### ISSUE TITLE
tsserver can't find file

### ISSUE THREAD

**Issue by vidjuheffex** [ananthakumaran/tide#264]
When submitting issues to this project, please include the following information.

## Checklist

- [ X] I have searched both open and closed issues and cannot find a duplicate.
- [ X] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [ ehhhh] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [ X] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [ ] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [ ] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [ ] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20180608.239
- TypeScript: whatever comes with tide
- Emacs: 26.1

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

Seems random. Just appears throughout during regular use. OFTEN.

## Expected Behavior

To not have missing files issues (Im not changing branches or anything)

## Actual Behavior

As I use tide throughout the day I get the following:
(NOTE: THE FILE IT CANT FIND IS THE OPEN FILE.)

Error: Could not find file: '/Users/julian/projects/designer/src/client/shared/components/droppable/index.js'.
    at getValidSourceFile (/Users/julian/.emacs.d/elpa/tide-20180608.239/tsserver/tsserver.js:107159:23)
    at Object.getQuickInfoAtPosition (/Users/julian/.emacs.d/elpa/tide-20180608.239/tsserver/tsserver.js:107391:30)
    at IOSession.Session.getQuickInfoWorker (/Users/julian/.emacs.d/elpa/tide-20180608.239/tsserver/tsserver.js:115149:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/julian/.emacs.d/elpa/tide-20180608.239/tsserver/tsserver.js:114211:61)
    at /Users/julian/.emacs.d/elpa/tide-20180608.239/tsserver/tsserver.js:115768:88
    at IOSession.Session.executeWithRequestId (/Users/julian/.emacs.d/elpa/tide-20180608.239/tsserver/tsserver.js:115759:28)
    at IOSession.Session.executeCommand (/Users/julian/.emacs.d/elpa/tide-20180608.239/tsserver/tsserver.js:115768:33)
    at IOSession.Session.onMessage (/Users/julian/.emacs.d/elpa/tide-20180608.239/tsserver/tsserver.js:115788:35)
    at Interface.<anonymous> (/Users/julian/.emacs.d/elpa/tide-20180608.239/tsserver/tsserver.js:117048:27)
    at emitOne (events.js:115:13)
    at Interface.emit (events.js:210:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:595:20)

Running tide-restart-server usually fixes this. But can reoccur as quickly as switching buffers, sometimes on opening a new file, etc. At this point, it is too often to ignore or 'just deal with it'.

The more details you provide, the better your chance of getting a speedy resolution.

**Comment by ananthakumaran** [comment]
This seems to be an issue at `tsserver` which is maintained at https://github.com/Microsoft/TypeScript/. They seem to have an open issue https://github.com/Microsoft/TypeScript/issues/20785, which looks like the same. Could you open a new issue there? Check https://github.com/ananthakumaran/tide#debugging section for how to capture the logs, which would be useful for debugging the issue.

**Comment by ananthakumaran** [comment]
closing this, please reopen if you think tide is at fault here.
